### ISSUE TITLE
Disk quota error

### ISSUE THREAD

**Issue by mbarnach** [IBM/swift-kitura-app#10]
Simply deploying the app on Cloud Foundry with `ibmcloud cf push` leads to a disk quota error.
Extending the disk quota to 2GB leads to the same error.

Only using the default Swift version allows the build to complete (currently 5.0.2 instead of 5.1).

**Comment by nfstein** [comment]
Thanks, we are looking into this

**Comment by gee4vee** [comment]
This is likely due to the build dir caching. Can you try this and then restage?
`cf set-env <app-name> SWIFT_BUILD_DIR_CACHE false`

**Comment by mbarnach** [comment]
It fixes the issue indeed! Thanks!
